// packages/react/src/components/VustGlassProvider/VustGlassProvider.tsx
import React, { useContext, useLayoutEffect, useMemo, useState } from "react";
import { glassContext, type VustGlassValue } from "../../glass";
import { observeGlassTokens } from "../../internal/glass-tokens";

export interface VustGlassProviderProps {
  /** 子树材质配置；省略时继承上层 Provider。 */
  glass?: VustGlassValue;
  children?: React.ReactNode;
}

/** 为普通子树与 Portal 浮层统一提供材质、主题和公共 Token。 */
export const VustGlassProvider: React.FC<VustGlassProviderProps> = ({
  glass,
  children,
}) => {
  const parent = useContext(glassContext);
  const [root, setRoot] = useState<HTMLDivElement | null>(null);
  const [theme, setTheme] = useState<string>();
  const [tokens, setTokens] = useState<Record<string, string>>({});

  useLayoutEffect(() => {
    if (!root) return;
    const read = () => {
      setTheme(
        root.closest("[data-theme]")?.getAttribute("data-theme") ?? undefined,
      );
      const style = getComputedStyle(root);
      const next: Record<string, string> = {};
      for (let index = 0; index < style.length; index += 1) {
        const property = style.item(index);
        if (property.startsWith("--vdl-"))
          next[property] = style.getPropertyValue(property);
      }
      setTokens((current) =>
        JSON.stringify(current) === JSON.stringify(next) ? current : next,
      );
    };
    read();
    return observeGlassTokens(root, read);
  }, [root]);

  const context = useMemo(
    () => ({
      value: glass ?? parent?.value,
      theme: theme ?? parent?.theme,
      tokens,
      scope: root ?? undefined,
    }),
    [glass, parent?.value, parent?.theme, root, theme, tokens],
  );

  return (
    <glassContext.Provider value={context}>
      <div
        ref={setRoot}
        style={{ display: "contents" }}
        data-ui="glass-provider"
      >
        {children}
      </div>
    </glassContext.Provider>
  );
};

// packages/vue/src/components/VustGlassProvider.vue
<script setup lang="ts">
import {
  computed,
  inject,
  onBeforeUnmount,
  onMounted,
  provide,
  ref,
} from "vue";
import { glassContext, type VustGlassValue } from "../glass";
import { observeGlassTokens } from "../internal/glass-tokens";

const props = withDefaults(defineProps<{ glass?: VustGlassValue }>(), {
  glass: undefined,
});
const parent = inject(glassContext, undefined);
const root = ref<HTMLElement>();
const theme = ref<string>();
const tokens = ref<Record<string, string>>({});
let stopTokens: (() => void) | undefined;
provide(glassContext, {
  value: computed(() => props.glass ?? parent?.value.value),
  theme: computed(() => theme.value ?? parent?.theme.value),
  tokens: computed(() => tokens.value),
  scope: computed(() => root.value),
});
onMounted(() => {
  const read = () => {
    theme.value =
      root.value?.closest("[data-theme]")?.getAttribute("data-theme") ??
      undefined;
    if (root.value) {
      const style = getComputedStyle(root.value);
      const next: Record<string, string> = {};
      for (let i = 0; i < style.length; i++) {
        const property = style.item(i);
        if (property.startsWith("--vdl-"))
          next[property] = style.getPropertyValue(property);
      }
      if (JSON.stringify(tokens.value) !== JSON.stringify(next))
        tokens.value = next;
    }
  };
  read();
  if (root.value) stopTokens = observeGlassTokens(root.value, read);
});
onBeforeUnmount(() => stopTokens?.());
</script>

<template>
  <div ref="root" style="display: contents" data-ui="glass-provider">
    <slot />
  </div>
</template>
